export const SCRIPT_LANGUAGES = [
  'English',
  'Spanish',
  'Hindi (हिंदी)',
  'Bengali (বাংলা)',
  'Tamil (தமிழ்)',
  'Telugu (తెలుగు)',
  'Marathi (मराठी)',
  'Gujarati (ગુજરાતી)',
  'Kannada (ಕನ್ನಡ)',
  'Malayalam (മലയാളം)',
  'Odia (ଓଡ଼ିଆ)',
  'Punjabi (ਪੰਜਾਬੀ)',
  'Assamese (অসমীয়া)',
  'Bodo',
  'Dogri',
  'Kashmiri',
  'Konkani',
  'Maithili',
  'Manipuri',
  'Nepali (नेपाली)',
  'Sanskrit (संस्कृतम्)',
  'Santali',
  'Sindhi',
  'Urdu (اردو)'
] as const;
